// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsjMzJEi8nZdAcKwzYBuJAlQANGIOC4QE',
    appId: '1:1053765609011:web:0f401dfe5fc016a7a7a546',
    messagingSenderId: '1053765609011',
    projectId: 'dzeroth-prod',
    authDomain: 'dzeroth-prod.firebaseapp.com',
    storageBucket: 'dzeroth-prod.firebasestorage.app',
    measurementId: 'G-TRYTXZ3EPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlOwNeGQJW2fpUHGaF7IipVG8aQ2xZeU',
    appId: '1:1053765609011:android:13592d83796f6ed7a7a546',
    messagingSenderId: '1053765609011',
    projectId: 'dzeroth-prod',
    storageBucket: 'dzeroth-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPTp1Z0xHcuscKceTsGPTGI_nekfOvZI',
    appId: '1:1053765609011:ios:c2813c9c08877e90a7a546',
    messagingSenderId: '1053765609011',
    projectId: 'dzeroth-prod',
    storageBucket: 'dzeroth-prod.firebasestorage.app',
    iosClientId: '1053765609011-eq8m7ft9f20guehbqeekc56v3dh08hf0.apps.googleusercontent.com',
    iosBundleId: 'com.dzeroth.dzeroth',
  );
}
