// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMnDceAmyyoN1Rx8wdUsqTHgFoyJyW1o',
    appId: '1:276998253227:web:75c8031d093e4d6280a5ee',
    messagingSenderId: '276998253227',
    projectId: 'dzeroth-dev',
    authDomain: 'dzeroth-dev.firebaseapp.com',
    storageBucket: 'dzeroth-dev.firebasestorage.app',
    measurementId: 'G-FH6BVXB47G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hjZRjeYtjI8dQTxfpKggMrWJ2VVTDVI',
    appId: '1:276998253227:android:2acbe7390ae3dfc180a5ee',
    messagingSenderId: '276998253227',
    projectId: 'dzeroth-dev',
    storageBucket: 'dzeroth-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQN_AbMn7QE7tDcxzrRsr3WeuJc4eWhE',
    appId: '1:276998253227:ios:25374eb2545939b380a5ee',
    messagingSenderId: '276998253227',
    projectId: 'dzeroth-dev',
    storageBucket: 'dzeroth-dev.firebasestorage.app',
    iosClientId: '276998253227-8cbo1n2auibiaoq64ue84e2ebavp0d5e.apps.googleusercontent.com',
    iosBundleId: 'com.dzeroth.dzeroth',
  );
}
